### ISSUE TITLE
Add GUI

### ISSUE THREAD

**Issue by lubaskinc0de** [DreWeRs/currency-converter#1]
### I'm suggest you to do:

1. Separated branch called dev for pushing development commits (holding release commits in master branch only)
2. Add the label "Enchancement" to this issue via github interface
3. After you finish working for next release in dev branch, you can create PR to master and merge it (via github interface)

### contact me if you have questions.

*Happy hacking!*

**Comment by DreWeRs** [comment]
Thanks for your ideas, a gui was added in the last commit, but I forgot to use PR. Also was added new branch dev
